# Generated by Django 5.2.7 on 2025-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_homepagesettings_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_heading', models.CharField(default='Welcome back, {{ user.first_name }}', help_text='Main heading text at the top of the dashboard.', max_length=150)),
                ('intro_text', models.TextField(blank=True, default='Here’s an overview of your account and quick access to your saved items.', help_text='Displayed under the welcome heading on the dashboard.', null=True)),
                ('support_url', models.URLField(blank=True, help_text='Optional custom URL for the support/contact page. Defaults to /support/.', null=True)),
                ('left_title', models.CharField(default='Get In Touch', help_text='Title for the left box on the support page.', max_length=100)),
                ('response_time', models.CharField(default='Within 48 hours (weekdays)', help_text='Displayed response time.', max_length=100)),
                ('support_hours', models.CharField(default='Monday – Friday, 9AM – 4PM GMT', help_text='Displayed support hours.', max_length=100)),
                ('policies_link', models.URLField(blank=True, help_text='Optional link to policies index page.', null=True)),
                ('docs_link', models.URLField(blank=True, help_text='Optional link to documentation page.', null=True)),
                ('help_item_1', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_2', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_3', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_4', models.CharField(blank=True, max_length=120, null=True)),
                ('help_item_5', models.CharField(blank=True, max_length=120, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
