# Generated by Django 5.2.7 on 2025-10-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dashboardsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsettings',
            name='welcome_heading',
            field=models.CharField(default='Welcome,', help_text='Main heading text at the top of the dashboard.', max_length=150),
        ),
    ]
