# Generated by Django 5.2.7 on 2025-10-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dashboardsettings_welcome_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='business_paragraph',
        ),
        migrations.RemoveField(
            model_name='homepagesettings',
            name='homepage_intro',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='closing_text',
            field=models.TextField(blank=True, help_text='Optional text box shown after the download CTA at the bottom of the homepage.', null=True, verbose_name='Closing Text (End of Homepage)'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_button_link',
            field=models.URLField(blank=True, help_text='Optional button link for the hero area (e.g. product or shop URL).', null=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, help_text="Optional button text for the hero area (e.g. 'Shop Now').", max_length=100, null=True),
        ),
    ]
