# Generated by Django 6.0 on 2025-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, help_text='Control the order of this page in the navigation.'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=True, help_text='Show this page in the footer links.'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_navigation',
            field=models.BooleanField(default=True, help_text='Show this page in the top navigation bar.'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='show_blog_on_homepage',
            field=models.BooleanField(default=False, help_text='Show the latest 3 blog posts on the homepage.'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='show_gallery_on_homepage',
            field=models.BooleanField(default=False, help_text='Show gallery images on the homepage.'),
        ),
    ]
