# Generated by Django 6.0 on 2025-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_galleryimage_page_menu_order_page_show_in_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
