# Generated by Django 6.0 on 2025-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_galleryimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('hero', 'Hero Section'), ('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List'), ('image_full', 'Full Width Image'), ('contact_form', 'Contact Form')], max_length=50),
        ),
    ]
