# Generated by Django 6.0 on 2025-12-09 15:30

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('video_url', models.CharField(blank=True, help_text='Paste a YouTube embed URL. Leave blank if using an image.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List'), ('contact_form', 'Contact Form')], max_length=50),
        ),
    ]
