# Generated by Django 6.0 on 2025-12-09 20:43

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_hero_alter_pagesection_section_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='video_url',
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_1_body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_1_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_2_body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_3_body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/columns/'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col_3_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('three_column', 'Three Column'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List'), ('contact_form', 'Contact Form')], max_length=50),
        ),
    ]
