# Generated by Django 6.0 on 2025-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_hero_video_url_pagesection_col_1_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content_block_1',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_block_2',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content_block_3',
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('home', 'Homepage'), ('about', 'About'), ('custom', 'Custom Page')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('content_blocks', 'Content Blocks (3 Column)'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List'), ('contact_form', 'Contact Form')], max_length=50),
        ),
    ]
