# Generated by Django 6.0 on 2025-12-09 22:29

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_page_content_block_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesection',
            name='col_1_body',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_1_image',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_1_title',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_2_body',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_2_image',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_2_title',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_3_body',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_3_image',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='col_3_title',
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('text', 'Text Block'), ('two_column', 'Two Column'), ('features', 'Features Grid'), ('cta', 'Call to Action'), ('faq', 'FAQ List'), ('contact_form', 'Contact Form')], max_length=50),
        ),
        migrations.CreateModel(
            name='ThreeColumnBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('col_1_title', models.CharField(blank=True, max_length=200)),
                ('col_1_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_1_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('col_2_title', models.CharField(blank=True, max_length=200)),
                ('col_2_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_2_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('col_3_title', models.CharField(blank=True, max_length=200)),
                ('col_3_body', tinymce.models.HTMLField(blank=True, null=True)),
                ('col_3_image', models.ImageField(blank=True, null=True, upload_to='pages/columns/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_columns', to='pages.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
