# Generated by Django 6.0 on 2025-12-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_pagesection_col_1_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='button_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
