# Generated by Django 6.0 on 2025-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pagesection_button_link_pagesection_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('cta', 'Call to Action'), ('faq', 'FAQ List'), ('features', 'Features Grid'), ('text', 'Text Block'), ('two_column', 'Two Column')], max_length=50),
        ),
    ]
