# Generated by Django 6.0 on 2025-12-12 08:04

from django.db import migrations


def remove_invalid_three_column_sections(apps, schema_editor):
    PageSection = apps.get_model("pages", "PageSection")
    PageSection.objects.filter(section_type="three_column").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_pagesection_section_type"),
    ]

    operations = [
        migrations.RunPython(remove_invalid_three_column_sections),
    ]
