# Generated by Django 6.0 on 2025-12-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_cleanup_three_column_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='pages.page')),
            ],
            options={
                'verbose_name': 'Gallery Block',
                'verbose_name_plural': 'Gallery Blocks',
                'ordering': ['order'],
            },
        ),
    ]
