# Generated by Django 6.0 on 2025-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_galleryimage_gallery_alter_galleryimage_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_1_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_2_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='threecolumnblock',
            name='col_3_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
