# Generated by Django 6.0 on 2025-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_alter_threecolumnblock_col_1_title_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE pages_pagesection
                DROP COLUMN IF EXISTS col_1_title,
                DROP COLUMN IF EXISTS col_1_body,
                DROP COLUMN IF EXISTS col_2_title,
                DROP COLUMN IF EXISTS col_2_body,
                DROP COLUMN IF EXISTS col_3_title,
                DROP COLUMN IF EXISTS col_3_body;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
