# Generated by Django 6.0 on 2025-12-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_drop_pagesection_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='show_shop_on_homepage',
            field=models.BooleanField(default=False, help_text='Show featured products on the homepage.'),
        ),
    ]
