# Generated by Django 5.2.7 on 2025-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_hour',
            field=models.PositiveIntegerField(blank=True, help_text='Price per hour in pence', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('download', 'Digital Download'), ('coaching', 'Service Hours')], default='download', max_length=20),
        ),
    ]
