# Generated by Django 5.2.7 on 2025-11-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price_per_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('download', 'Digital Download')], default='download', max_length=20),
        ),
    ]
